name: Wiki
description: |
  wiki
version: 0 # Version of the Catalog to be used
category: 1 # Category to be used for searching catalog entries
maintainer: 1337pwny <do5frx@itgrufti.de>
license: no # The license
projectURL: URL # A URL related to the catalog entry
